### ISSUE TITLE
Testing & `MockTracer`

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#10]
In OT there is an in-memory `Tracer` instance called `MockTracer` (https://github.com/opentracing/opentracing-java/blob/master/opentracing-mock/src/main/java/io/opentracing/mock/MockTracer.java), used to test library instrumentation - essentially you provide a `Tracer` instance on which such instrumentation works.

Afterwards, finished `Span` objects can be checked (along with their operation name, tags, logs, etc), as shown in the OkHttp instrumentation: https://github.com/opentracing-contrib/java-okhttp/blob/master/opentracing-okhttp3/src/test/java/io/opentracing/contrib/okhttp3/AbstractOkHttpTest.java#L76

```java
        MockTracer mockTracer = new MockTracer(new ThreadLocalScopeManager(), 
             MockTracer.Propagator.TEXT_MAP);
        ...
        List<MockSpan> mockSpans = mockTracer.finishedSpans();
        Assert.assertEquals(2, mockSpans.size());

        MockSpan networkSpan = mockSpans.get(0);
        Assert.assertEquals(8, networkSpan.tags().size());
        Assert.assertEquals(Tags.SPAN_KIND_CLIENT, 
                            networkSpan.tags().get(Tags.SPAN_KIND.getKey()));
```

The requirement then is to:

1. Obtain a `Tracer` instance, used by code testing instrumentation logic.
2. Later fetch information about the resulting `Span` objects - status overall.

My impression is that, yes, this could be achieved through a in-memory exporter - but I'm wondering how user-friendly that is.

Let me know ;)

**Comment by yurishkuro** [comment]
I feel that in OT the mock tracer was a necessity because there was no reference implementation, but if we have OC reincarnation as OpenFoo default implementation, I would prefer not to have a separate mock tracer. Or, we can have it as a wrapper over default implementation, if we want the convenience of tracer.getFinishedSpans(). It would then hide the exporter.

**Comment by carlosalberto** [comment]
> we can have it as a wrapper over default implementation, if we want the convenience of tracer.getFinishedSpans(). It would then hide the exporter.

I really like this idea (and it would be an alternative to the in-memory exporter).

**Comment by bogdandrutu** [comment]
I think we agreed on this, it just needs to be implemented. I will add a label "Agreed".

**Comment by SergeyKanzhelev** [comment]
closing as we agreed and no action items required at this point
