### ISSUE TITLE
Rename Tracer.spanBuilderWithRemoteParent()

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#108]
As the remote info has been removed from `SpanData`, I'm wondering if it makes sense to rename `Tracer.spanBuilderWithRemoteParent()` to be simply `Tracer.spanBuilderWithExplicitParent()` (it would exist as an overload that takes a `SpanContext` instead of a `Span`).

**Comment by carlosalberto** [comment]
On second thought: I realized that samplers take a `hasRemoveParent` parameter. So in that case we would need to keep the current `spanBuilderWithRemoteParent()` name.

**Comment by tedsuo** [comment]
Issue: we don't want spans with in-process parents to be created from a `SpanContext`, as we would like to use a monotonic clock. So if we have a builder that creates a Span parent from a `SpanContext`, we want to indicate it should only be used for edge spans. So we will leave the current message signature.
