### ISSUE TITLE
Do we need both HTTP and TEXT_MAP carrier types?

### ISSUE THREAD

**Issue by tedsuo** [bogdandrutu/openconsensus#127]
TEXT_MAP is simply a less restrictive version of the HTTP carrier type. Since all systems must realistically be compatible with HTTP, this has not turned out to be a useful concept in practice. There are non-binary carriers other than HTTP headers which can have further restrictions (JMS for example). But a more open carrier type does not help handle these scenarios.

We propose to eliminate the separate HTTP carrier type. The TEXT_MAP encoding will now be required to conform to HTTP 1.1 header semantics.

**Comment by tedsuo** [comment]
Action Item: change documentation to mention this restriction.

**Comment by tedsuo** [comment]
Do we call this HTTP_TEXT_MAP? :)

**Comment by carlosalberto** [comment]
`HTTP_TEXT_MAP` sounds great to me.  `HTTP_MAP` is another alternative.

**Comment by bogdandrutu** [comment]
@carlosalberto can you fix this today?

**Comment by carlosalberto** [comment]
Sure ;)
