### ISSUE TITLE
Message Events

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#13]
OT: Nothing like this exists.

OC: Defines this additional API.
Possible approaches:
Implement this is a specialized form of log/annotation (NOTE: Bogdan doesn’t like this. Might need to do further research of how this is handled underneath).
Keep this as an additional/separated API, but keep it abstract, so each Tracer implementation can choose whatever way to handle they want.
Do not expose it at the public level, but keep it as a OC specific feature.

**Comment by tedsuo** [comment]
Logs have now become Events. We would like `MessageEvent` to become a specialized type of `Event`, and to have events be extensible in the new project. 

@bogdandrutu do you have a plan for the first iteration of this? I believe you had an idea as to how you would like to see this modeled.

**Comment by yurishkuro** [comment]
We already added `span.addEvent(Event)` API, so it's not that difficult to start adding specialized versions of the events.

**Comment by tedsuo** [comment]
Solution:
* `Event` is an interface which produces an `EventData` object (name plus attributes).
* `MessageEvent` conforms to `Event`, and it's `EventData` which includes standard attributes.
* `EventData` is not a finalized name yet.

**Comment by bogdandrutu** [comment]
I think this is resolved.
