### ISSUE TITLE
OC Attributes vs. OT Tags

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#15]
OC “Attributes” and OT “Tags” (not OC tags) are key value pairs used to decorate Spans with information.
OT Tag
public abstract class AbstractTag<T> implements Tag<T> {
    public String getKey();
    public abstract void set(Span span, T tagValue);
}
public class StringTag extends AbstractTag<String> {
    public StringTag(String key) {}

    @Override
    public void set(Span span, String tagValue) {}
}
OC Attribute
public abstract class AttributeValue {
  public static AttributeValue stringAttributeValue(String stringValue);
  public static AttributeValue booleanAttributeValue(boolean booleanValue);
  public static AttributeValue longAttributeValue(long longValue);
  public static AttributeValue doubleAttributeValue(double doubleValue);
  public abstract <T> T match(
      Function<? super String, T> stringFunction,
      Function<? super Boolean, T> booleanFunction,
      Function<? super Long, T> longFunction,
      Function<? super Double, T> doubleFunction,
      Function<Object, T> defaultFunction);
}
abstract static class AttributeValueString extends AttributeValue {
    abstract String getStringValue();
}
Differences
In OC, Spans, Annotations and Links can contain attributes. In OT, only Spans have Tags.
In OT, Tag objects are used as helpers to set a tag value, while in OC they are used as containers for boolean/string/double values.
Proposed Resolutions
Remove Attributes from Links 
Alternatively, add tags to References. But we need to explain why they are important, how they are different from attributes on Spans, and what it means for tracers to support them, as opposed to just putting the tags on the spans.
Questions
Where do these attributes go when they are exported to various backends?

**Comment by SergeyKanzhelev** [comment]
[sergey] everybody (bogdan, ted, Carlos, yuri) like attributes better

**Comment by SergeyKanzhelev** [comment]
Yay! closed

**Comment by SergeyKanzhelev** [comment]
oops... we should revisit match pattern.

**Comment by SergeyKanzhelev** [comment]
@carlosalberto will propose replacement for match pattern

**Comment by bogdandrutu** [comment]
This is done as it was written initially.
