### ISSUE TITLE
Do we need childSpanCount on SpanData

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#156]
What's the use case to have `childSpanCount` in API?

We eliminated scenario when span data produced by SDK can be re-consumed by API as we removed all the dropped events counts. Perhaps this is in the same category of non-needed for API surface

**Comment by bogdandrutu** [comment]
This can be used by the backends to determine when a trace is completed, if someone pushes spans this information may be needed.

**Comment by tedsuo** [comment]
Decision: This will be on the protobuf, but not on `SpanData`.

For out-of-band recording, it is generally not possible to know this information, so it is not useful in that scenario.
