### ISSUE TITLE
Attribute types

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#18]
OC has limited set of primitives, OT has more types even an object

**Comment by SergeyKanzhelev** [comment]
no objects. In OT it is theoretically possible, but it is a misuse

**Comment by SergeyKanzhelev** [comment]
support double and int instead of Number

**Comment by SergeyKanzhelev** [comment]
in future we may add lazyString attribute type.

**Comment by bogdandrutu** [comment]
Remove from ot the generic interface that accepts template.

**Comment by yurishkuro** [comment]
In terms of the interface, I would prefer something like this:
```
interface AttributeContainer {
    void setAttribute(String key, String value)
    void setAttribute(String key, int value)
    void setAttribute(String key, bool value)
    void setAttribute(Attribute attr)
}
```
The reason is that if we always insist on passing Attribute object, it means I always have to do memory allocations, even though the implementation of the API can be optimized to not require those.

**Comment by bogdandrutu** [comment]
@yurishkuro can you clarify on the difference, do you suggest to remove AttributeValue from the API and accept primitives?
