### ISSUE TITLE
Allow update of Span name.

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#23]
In order to support a bridge to OT, we need to allow `Span`'s name to be updated.

The method that requires this, from the OT side, is `Span.setOperationName()`.

**Comment by bogdandrutu** [comment]
I think we also discussed two things:
* How to enforce that the Span at the end() call has a name set.
* Consider maybe updateName and enforce start span to get a name and allow updating the name later.

**Comment by carlosalberto** [comment]
Yeah, was wondering about the `updateName()` as discussed in the call - it does *feel* weird, among the `set*()` methods though ;)

So at this moment, we are already requiring (from OT and the new API) that a `Span` has a name, no?When `SpanBuilder`s are created, this is required:

```java
// OT
Tracer.buildSpan("spanName");

// New API
Tracer.spanBuilder("spanName");
```

**Comment by SergeyKanzhelev** [comment]
Maybe `putName` to align with `putAttribute`?

@bogdandrutu - as Carlos said, builder already requires name on construction in both. So this part should be good. Do you have anything else in mind?

**Comment by bogdandrutu** [comment]
Proposal: setName vs updateName

**Comment by bogdandrutu** [comment]
Decision: Go with update, if strong opinions from community then we may revisit.

**Comment by yurishkuro** [comment]
Does OC redo the sampling decision today once the span name is changed?

The Adaptive Sampling in Jaeger is done per span name (not per service), and having to support late binding of the span names was pretty painful.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro name update only available in C# I believe. We discussed whether we need to update sampling decision but decided against it. One of reasoning was that perhaps this kind of sampling should work on the pipe after all the data is collected. So customer will need to configure it differently when she knows that this update is probably happening.

**Comment by yurishkuro** [comment]
If the service makes downstream calls, the sampling decision needs to be made before those calls. The typical use case for overriding span name is when instrumentation doesn't know the name immediately upon receiving the inbound request (e.g. if the span is created lower in the networking stack), but usually it is available and set long before the service handler is invoked and it can make downstream calls.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro, yes it is valid point. How did you solve it in Jaeger?

Perhaps we can only allow the change of span name via the method on tracer? So tracer will be able to re-apply sampling. 

One big problem with `updateName` - it is typicaly that you don't know whether you will definitely need to update the name or not.

**Comment by bogdandrutu** [comment]
What about having an attribute "displayName" that can be used by the backends to show better name? Or maybe a better attribute key name?

**Comment by tedsuo** [comment]
We've decided to go with `Span.updateName()` for this feature.

**Comment by tedsuo** [comment]
TODO: include documentation describing the relationship between updating the operation name, and sampling decisions based on the operation name.
