### ISSUE TITLE
putAttribute vs. setAttribute

### ISSUE THREAD

**Issue by yurishkuro** [bogdandrutu/openconsensus#25]
I am just curious if there was some consideration behind the `put` name, and if so to document it here.

**Comment by SergeyKanzhelev** [comment]
my understanding was always that `set` has a semantics of first and only write. `put` is used as "create or overwrite". But I never put much thoughts into it. So worth discussing.

Is it `set` in OT?

**Comment by bogdandrutu** [comment]
I think this is very language specific. In Java we went with the "map" terminology of put, and it has the same semantics.

**Comment by yurishkuro** [comment]
@SergeyKanzhelev yes, it's SetTag/setTag/set_tag in OT Go/Java/Python

@bogdandrutu are you saying the name would change in a different language? That will probably be rather confusing.

**Comment by SergeyKanzhelev** [comment]
I'm fine either way

**Comment by bogdandrutu** [comment]
@yurishkuro If we want to have generic names I am fine with that, though some java devs will get confused about terminology.

One option is to use standard terminology for all these "map" like operations (we use this in tags in golang):
* insert - If k already exists, doesn't update the value.
* update - If k doesn't exists, doesn't insert the value.
* upsert - It inserts the value if k doesn't exist already, it updates the value if k already exists.
* delete - deletes the value associated with keys.

**Comment by yurishkuro** [comment]
I prefer not over to complicate things. `set` is similar to classic setters, the upsert semantics of it seems universal. While `put` is very Java-centric, many other languages don't have an equivalent.

The one caveat from OT is that SetTag() had unspecified behavior if called more than once with the same key. This wasn't related to `set` vs `put`, more to the implementation and efficiency (e.g. Jaeger keeps KVs in array, rather than a map, so guaranteeing uniqueness would actually be extra work). There was never a particularly strong use case for the multi-map semantic.

**Comment by bogdandrutu** [comment]
I agree that the implementation can keep everything in an array, but when exported to you dedup?

**Comment by yurishkuro** [comment]
You can, but it's still extra CPU cycles and memory allocations that become necessary if the API semantics require key uniqueness.

**Comment by bogdandrutu** [comment]
Then we should say that attributes is a List<Pair<Key, Value>>, so a better name is "addAttribute" probably.

**Comment by carlosalberto** [comment]
> I prefer not over to complicate things. set is similar to classic setters, the upsert semantics of it seems universal. While put is very Java-centric, many other languages don't have an equivalent.

I agree on this one - I think we can either go with `addAttribute` or `setAttribute`, even if it's not so Java centric.

**Comment by bogdandrutu** [comment]
Decision: setAttributes, the behavior is a List of attributes and if the backend dedups then the ordering should be guaranteed.
