### ISSUE TITLE
Rename Tracer.withSpan() to something more meaningful

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#28]
`Tracer.withSpan(Span)` sets the specified `Span` as the active/current instance - but personally I think the name is not meaningful enough.

Would it make sense to change it to `Tracer.activateSpan()` as we call it in OT? I'm open to alternatives too ;)

**Comment by yurishkuro** [comment]
+1, perhaps even shorter, tracer.activate(span)

**Comment by carlosalberto** [comment]
`Tracer.activate()` would work for me ;)

**Comment by tedsuo** [comment]
@bogdandrutu does `Tracer.activate()` work for you?

**Comment by bogdandrutu** [comment]
I think withSpan is better in my opinion. It matches with other languages like go (where calling this activate would be an anti-pattern).

**Comment by carlosalberto** [comment]
So if `activate` would sound bad for go, we can use something else.

Personally I think `withSpan()` totally lacks meaning (no mention about it becoming the current `Span` or anything.

**Comment by tedsuo** [comment]
Let's go with `Tracer.with(span)`. This is very clear:

```java
import io.openfoo

public void startWork(){
	Span span = openfoo.tracer().startSpan(“My Span”);
	span.setAttribute(“someTagKey”, “someTagValue”)
  try (Scope s = tracer.with(span)) {
	finishWork();
  }
}
public void finishWork(){
	Span span = openfoo.tracer().getCurrentSpan();
	span.event(“some log”);
	span.finish();
}
```

@carlosalberto @yurishkuro how do you feel about this?

**Comment by yurishkuro** [comment]
I assume in Go it would be more like

ctx=tracing.WithSpan(ctx, span)

Which is (and much clearer) than tracer.with(span). I agree that the latter does not explain what happens. 

I think this is one area where language parity is not the goal, eg in Python tracer.start_span() already activates it

**Comment by bogdandrutu** [comment]
Conclusion: we stay with `withSpan` for the moment.

**Comment by tylerbenson** [comment]
I can accept `withSpan` and so won't reopen the issue, but just wanted to throw out one other idea:  `scoped` or `scopedWith`

```java
Span span = tracer.startSpan(“My Span”);
try (Scope s = tracer.scopedWith(span)) {
    finishWork();
} finally {
  span.finish();
}
```

and extending Yuri's example for go:
```go
ctx=tracing.ScopedWith(ctx, span)
```

I like this because it has the properties of being short, not overly verbose given proper variable naming of `span`, and also better implicit indication of the behavior of the method.
