### ISSUE TITLE
Rough port of OpenCensus for testing purposes

### ISSUE THREAD

**Issue by tedsuo** [bogdandrutu/openconsensus#3]
- [x] Initial rough port of OC
- [ ] Review starting point
- [ ] Adjust terminology to match new terms for the new project

**Comment by bogdandrutu** [comment]
I think I done the initial port.

**Comment by bogdandrutu** [comment]
Caveats:
* No propagation api for the moment.
* No tags yet (coming soon).
* No stats/metrics yet (coming soon).

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu looks good for me! I see you did a few movement of classes. Are those renames made with a commit that we can later track down?

Just checking on the feeling from the group. Would it be faster to bring all APIs from Open Census and work from there? I kind of missing tags and metrics, especially if we plan renames. And I fill it may be easier to track down changes later if we will start with exact copy of an Open Census to bring implementation to work with the new API. @carlosalberto @yurishkuro what do you think?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev I can do that if you think is easier, let me know what others think.

@tedsuo I fixed the javadoc issues.

**Comment by carlosalberto** [comment]
Hey hey, thanks a lot for creating the initial code import :) 

So I did a first quick pass and I have a few things to comment (wasn't sure on whether I should create an Issue per each, so I will mention these things here first ;) )

* Sampling - As per the "Important Merge Items" doc, it was mentioned that at the moment, DDog expects (as LS) all Spans to be send to the exporter, where the vendor specific code would be deciding on the sampling (https://docs.google.com/document/d/1WhmNrl7ZGBTYAyo23OjTW7IXj2G4AtsTcwv3Zieg2tk/edit#heading=h.n3gmlwixfbau). I'm wondering if using the `alwaysSample()` Sampler can be enforced for some vendors (or else, tell the users about this). ** Another option is to not have sampling here, but move it to the implementation-specific side (the SDK, that is).
* I don't think we came to a resolution on how to proceed with `MessageEvent`s (https://docs.google.com/document/d/1WhmNrl7ZGBTYAyo23OjTW7IXj2G4AtsTcwv3Zieg2tk/edit#heading=h.ck0lox8wqmr6)
* In OT we have a `MockTracer` that lets people test our their instrumentation. Would it be ok to add one here?
* Organization-wise, I'm wondering if `BlankSpan` and related classes could be put in their own `noop` sub-artifact?

On @SergeyKanzhelev suggestion, I'm fine with it (we can always refactor/change it later). Probably the one that doesn't fully fit into this one is context propagation, though ;)

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu let's start with the "as-is" copy of Open Census, please? Event for context propagation it's easier to make changes than writing brand new code.

**Comment by SergeyKanzhelev** [comment]
> In OT we have a `MockTracer` that lets people test out their instrumentation. Would it be ok to add one here?

Would it be enough to configure test exporter for tests?

**Comment by SergeyKanzhelev** [comment]
> Organization-wise, I'm wondering if `BlankSpan` and related classes could be put in their own noop sub-artifact?

@carlosalberto how do you want to use that separate artifact? Do you envision it can be used separately from the API? Or you just want a separate namespace?

The way I see it - BlankSpan can be internal. Per my understanding it is mostly used as a noop instrumentation to eliminate the need to have too many null checks.

**Comment by carlosalberto** [comment]
Hey hey @SergeyKanzhelev 

> Would it be enough to configure test exporter for tests?

Probably it would work... I'm wondering how easy would it be for users to write tests based on such exporter. Something we can consider and test out, yes ;)

> how do you want to use that separate artifact? Do you envision it can be used separately from the API? Or you just want a separate namespace?

Only a separate namespace ;)

>  it is mostly used as a noop instrumentation to eliminate the need to have too many null checks.

In OT having the no-op as public was helpful in case scenarios - not something important at this moment, but worth considering ;)

**Comment by tedsuo** [comment]
The remaining items in this issue are about finalizing the new interface, and covered by https://github.com/bogdandrutu/openconsensus/issues/2. I'm going to close this issue to show that we made progress to the point of having a running port of OpenCensus.
