### ISSUE TITLE
Remove SpanBuilder.startScopedSpan()

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#33]
As part of OT 0.32 we deprecated a few members (https://github.com/opentracing/opentracing-java/issues/291 details the reasons to do this).

As part of this, I'd also like to see `startScopedSpan()` gone.

**Comment by tedsuo** [comment]
Need @bogdandrutu to make this call.

@carlosalberto can you add a TL DR as to the reasoning for it's removal?

**Comment by carlosalberto** [comment]
So we are actually trying to prevent bad use of the API:

```java
try (Scope scope = tracer.spanBuilder("myOperation").startScopedSpan()) {
} catch (IOException e) {
  // scope/span are gone, there's no way to report errors.
}
```

Instead, we are asking the users to do this:

```java
Span span = tracer.buildSpan("myOperation").startSpan();
try (Scope scope = tracer.withSpan(span)) {
} catch (IOException e) {
  span.putAttribute(...);
} finally {
  span.end();
}
```

The OC documentation **does** mention this, but nevertheless, we would go a little bit far and remove this one ;)

**Comment by bogdandrutu** [comment]
Fine to remove it in the first version of the API and revisit this for a newer version.
