### ISSUE TITLE
Do not throw SpanContextParseException upon extraction

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#36]
Currently, the formats exposed by this API throw a `SpanContextParseException` upon `extract()` if the data is malformed - I think we should instead simply return `null` for this case.

**Comment by bogdandrutu** [comment]
I think this is very language specific, and using exceptions vs returning an "error" is a long subject. The main reason to throw an exception is to distinguish between malformed encoding vs missing encoding, if that is not necessary we can drop the exception.

**Comment by carlosalberto** [comment]
So my impression is that, at least when doing instrumentation, you don't really care about whether it was a malformed or a missing context info - you care only about whether you got it or not.

**Comment by bogdandrutu** [comment]
@carlosalberto please also do the same for tags (baggages).

**Comment by carlosalberto** [comment]
Shall I do that in another PR? It seems they are also using another Exception(s).

**Comment by yurishkuro** [comment]
+1 to no exception.
