### ISSUE TITLE
Support timestamp for Span.addEvent()

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#37]
We need this to have the OT bridge - related to #22 it seems to be ;)

**Comment by bogdandrutu** [comment]
Allowing users to set a timestamp for any event (start, event, end) will make hard for implementations to use a monotonic clock that can ensure ordering of events (you cannot control how the timestamp is retrieve when the user can provide it). Also allowing this functionality you cannot ensure that all the events timestamp are in the interval [start, end].

Can you give me some examples where this is needed?

**Comment by bogdandrutu** [comment]
@carlosalberto I heard that this was resolved.

**Comment by carlosalberto** [comment]
Closing this one.
