### ISSUE TITLE
confirm we can ignore span.kind after Span was created

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#42]
`Span` doesn't allow to set `span.kind`. Confirm we OK with this and ok to ignore setting this tag in OT shim

**Comment by yurishkuro** [comment]
hm, I see very often that tags are set on the span after creation

**Comment by SergeyKanzhelev** [comment]
should we expose setting the `Kind` on `Span` giving it's a strongly typed field? Would you always know the `Kind`?

**Comment by bogdandrutu** [comment]
I think in all the implementations this detailed is known at the Span creation time. If that is not the case please show an example when that is not the case.

**Comment by SergeyKanzhelev** [comment]
another question - should it be a part of `SpanBuilder` constructor than? Same as a name

**Comment by SergeyKanzhelev** [comment]
created issue for this:

> another question - should it be a part of SpanBuilder constructor than? Same as a name

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev should we close this issue?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev ping on this one.
