### ISSUE TITLE
Sampling on the API and exporter layer

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#45]
Based on previous feedback, some vendors wanted to have control of sampling at the exporter level - but sampling still exists at the API. I feel like we should probably do a clarification -for the users- on sampling at the api level AND (possible) sampling at the exporter level?

Also: for vendors subscribing to the API but not using the SDK, they might simply ignore the sampling info on our side.

(a possible action item is to have sampling with a default value specified by `Tracer`/`Tracing`, so each tracer provides the default API sampling decision).

Otherwise, we might revisit this item ;)

**Comment by tedsuo** [comment]
Conclusion: Clarify that the sampling option on the `SpanBuilder` is only a hint.

TODO: clarify documentation.

**Comment by carlosalberto** [comment]
Closing as #110 has been merged (#109 is rather a related polish item, not a requirement).
