### ISSUE TITLE
Remove match pattern for stats

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#48]
There is one more use of match pattern in API. Needs to be replaced with `getType` as well

**Comment by SergeyKanzhelev** [comment]
This function will need to be removed after it:

```
public interface Function<A, B> {

  /**
   * Applies the function to the given argument.
   *
   * @param arg the argument to the function.
   * @return the result of the function.
   * @since 0.1.0
   */
  B apply(A arg);
}
```

**Comment by bogdandrutu** [comment]
@songy23 can you help us with this?

**Comment by bogdandrutu** [comment]
@songy23 see the AttributeValue example + the latest PR about moving type as a inner class to AttributeValue

**Comment by songy23** [comment]
@bogdandrutu can you add me as a collaborator to this repo? Currently I don't have write access and cannot assign issues/request reviews.
