### ISSUE TITLE
Should default for Span.Kind be Undefined or Client

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#56]
Sub. Also, should we ask for `spanKind` in a constructor of a `SpanBuilder`?

**Comment by bogdandrutu** [comment]
I think Undefined is better because most of the user constructed Spans will not be client or server (these will be constructed by our instrumentation).

**Comment by SergeyKanzhelev** [comment]
So Undefined for you means in-between of `client` and `server`? Should we give a better name?

**Comment by bogdandrutu** [comment]
Maybe local span?

**Comment by SergeyKanzhelev** [comment]
I was thinking the same. So we will not have value of `Undefined` that may mean not defined yet.

**Comment by yurishkuro** [comment]
Is it documented somewhere why span.kind is `required`?  Obviously, it is a very helpful attribute, but many analysis tools still work if it's not present.

**Comment by tedsuo** [comment]
Conclusion:
* `Internal` is a good name for the default. 
* Add optional `SetSpanKind` method only on `SpanBuilder`.
