### ISSUE TITLE
Attributes in Links

### ISSUE THREAD

**Issue by carlosalberto** [bogdandrutu/openconsensus#57]
This is not something we support in OT at the moment, and don't think many vendors support this underneath either.

**Comment by SergeyKanzhelev** [comment]
so this is a "new" feature for Open Tracing. Is it a problem?

**Comment by carlosalberto** [comment]
So as they are not the same feature (References and Links), I'm closing it indeed.

**Comment by carlosalberto** [comment]
(Addressed by #14)
