### ISSUE TITLE
Link.Attributes limit is not enforced

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#60]
`SpanData` uses `Link` class, same as `Span`. So `getAttributes` on `Link` returns the map of attributes and cannot return `droppedAttributesCount`. So the limit on number of allowed attributes in not enforced in runtime as for `Span` attributes and there is no way to express the fact that the number of attributes was limited when creating a `SpanData`.

**Comment by SergeyKanzhelev** [comment]
should be able to construct `SpanData` and specify how many attributes were dropped for the `Link`

**Comment by tedsuo** [comment]
Conclusion: we'll track this in #74
