### ISSUE TITLE
Consistent Noop implementation

### ISSUE THREAD

**Issue by bogdandrutu** [bogdandrutu/openconsensus#65]
Currently for stats/tags we use a noop class that implements all the api vs in trace every class implements it's own noop. We should be consistent.

**Comment by bogdandrutu** [comment]
@songy23 wait for an agreement before coding this.

**Comment by tedsuo** [comment]
Conclusion:
* Noop will be part of main package

Question:
* Do we need to expose Noop for our users? What are the use cases?
* @carlosalberto will query the OT community.

**Comment by bogdandrutu** [comment]
@carlosalberto this is on you now.

**Comment by bogdandrutu** [comment]
Friendly ping on this.

**Comment by carlosalberto** [comment]
Based on initial feedback, it looks like having a no-op `Tracer` would be a nice to have, with the rest of the components staying private.

About the scenarios, didn't get much info, other than having the option to 'force' the global Tracer to stay no-op for a given case (which was something we may not need if we go with the ServiceLoader-alike approach).

**Comment by tedsuo** [comment]
We will expose Noop Tracer as a type, for situations when a component or function is requesting a Tracer reference.

Instead of Noop, we may want to have a "Propagation Only" tracer implementation, which propagates context only.

**Comment by songy23** [comment]
> However, instead of a pure Noop, we may want to have a "Propagation Only" tracer implementation, which propagates context only.
> Depending on how context propagation ends up working, it will either be a "minimal" tracer or a "noop" tracer.

Maybe file a separate issue to keep track of this?

**Comment by SergeyKanzhelev** [comment]
Issue already filed: https://github.com/bogdandrutu/openconsensus/issues/118
