### ISSUE TITLE
Bridge from the new SDK to current OT interfaces

### ISSUE THREAD

**Issue by tedsuo** [bogdandrutu/openconsensus#7]
* maintains backwards compatibility.
* allows for progressive adoption of new interfaces.

**Comment by bogdandrutu** [comment]
@tedsuo what is the difference between this and https://github.com/bogdandrutu/openconsensus/issues/4???

**Comment by SergeyKanzhelev** [comment]
let's close. Seems to be a dup. @tedsuo, please re-open if it is not
