### ISSUE TITLE
The stats/metrics getType pattern does not allow access to the value.

### ISSUE THREAD

**Issue by bogdandrutu** [bogdandrutu/openconsensus#70]
1. Decide if the right pattern is to have a getValueX on the super class or every sub-class implements a getValue and user has to convert the class to the sub-class.

@songy23 please make sure that the classes you modified allow access to the value using the decision from this issue.

**Comment by tedsuo** [comment]
option 1: switch on Enum + cast + get Value
PRO: 
* smaller public API
CON:
* casts everywhere

option 2: switch on Enum + getXValue
PRO: 
* no cast
CON:
* larger surface area
