### ISSUE TITLE
Simplify SpanData

### ISSUE THREAD

**Issue by bogdandrutu** [bogdandrutu/openconsensus#74]
Consider to be removed:
* Has remote parent

Currently SpanData is written as a result of the default implementation for the Span (including notions like dropped events). Maybe we should simplify this and the SpanData defined in the API does not include dropped events, and in the SDK (default implementation) we use directly the protos which include the notion of dropped events.

**Comment by carlosalberto** [comment]
Makes sense to me.

**Comment by tedsuo** [comment]
This is a good separation between a logical description of a trace, and information describing the state of the tracing system.

Concern:
* If the tracing runtime is taking action to conserve resources, such as dropping events, do we need to convey this information to the exporter? Should we be doing this sort of resource management?

SpanData is used for data representation of API:
* Exporter consumes SpanData
* Users describing out-of-band spans

**Comment by bogdandrutu** [comment]
@tedsuo I think Exporter will not consume SpanData. SpanData is just for users to describe out-of-band spans.

**Comment by tedsuo** [comment]
@bogdandrutu ok, so this is a subset of the protobuf object, which only contains fields that the user can set (including timestamps in this case).
