### ISSUE TITLE
Resource reference on Span

### ISSUE THREAD

**Issue by SergeyKanzhelev** [bogdandrutu/openconsensus#83]
Do we need an explicit resource reference on `Span`?

**Comment by bogdandrutu** [comment]
I think all the Spans started from a given Tracer belong to the same Resource as the Tracer.

**Comment by SergeyKanzhelev** [comment]
One minor issue here that we need to decide how to address is, let's say we have integration that collects HTTP client spans from multi-tenant app (multiple apps in a single process). That we need to inject proper tracer there somehow. It may be more natural in those cases take resource from the current context or somehting...

I'm not sure how important this right now. We can always get back to it later. Closing in favor of #84
